cd ..
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_3_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_3_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_8e-05_5_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_8e-05_5_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_3_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_3_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.1_0.008_5_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.1 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.1_0.008_5_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_3_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_3_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_8e-05_5_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 8e-05 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_8e-05_5_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_3_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 3 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_3_5_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_3_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_3_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_3_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_3_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_3_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_3_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_3_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 3 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_3_0.2/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_5_0.02/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_5_0.02/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_5_0.02/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.02 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_5_0.02/81911/'
wait
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adam --exps_dir 'exps/grid_search/triplet_adam_0.5_0.008_5_5_0.2/81911/' &
CUDA_VISIBLE_DEVICES=0 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_5_0.2/42/' &
CUDA_VISIBLE_DEVICES=1 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_5_0.2/77/' &
CUDA_VISIBLE_DEVICES=2 python TrainingAnomalyDetector_public.py --features_path 'data/anomaly_features' --annotation_path 'Train_Annotation.txt' --network_name 'TripletAnomalyDetector' --objective_name 'triplet_objective_sampling' --lr_base 0.01 --epochs 20 --output_dim 128 --dropout_rate 0.5 --lambdas 0.008 --top_anomaly_frames 5 --top_normal_frames 5 --margin 0.2 --optimizer adadelta --exps_dir 'exps/grid_search/triplet_adadelta_0.5_0.008_5_5_0.2/81911/'
wait